label variable folio "Folio"
label variable trim "Trimestre de aplicación"
label variable unidad "Unidad (Día-año-mes)"
label variable region "Región de aplicación del cuestionario"
label variable reg_mue "Región de muestreo"
label variable cd_mue "Ciudad de muestreo"
label variable zona_mue "Zona de muestreo"
label variable punt_mue "Punto de muestreo"
label variable turno "Turno"
label variable sexo "Sexo"
label variable edad "¿Cuántos años cumplidos tiene usted?"
label variable pai_nac "¿Dónde nació usted?"
label variable origen "¿Es usted de origen mexicano o mexicoamericano?"
label variable vive "¿Vive usted aquí en _________?"
label variable pais_vive "¿En qué país vive?"
label variable razon "¿A cuál de las siguientes razones se debe su visita a la zona fronteriza:"
label variable trabaja "¿Tiene usted trabajo en su lugar de procedencia o alguna fecha comprometida para su regreso?"
label variable lug_des "LUGAR DE DESTINO"
label variable p1 "¿Viene usted solo o acompañado en este viaje?"
label variable p1_1 "¿Cuántas personas lo acompañan?"
label variable p1_2 "¿Cuántas de ellas son menores de 15 años?"
label variable p1_3 "¿Cuántas de ellas son sus padres, hermanos, hijos o esposa?"
label variable p1_4 " De las personas que lo acompañan, ¿cuántas nacieron en México?"
label variable p1_5 " De las personas que lo acompañan, ¿cuántas son mujeres?"
label variable p2 "¿Habla usted algún dialecto o lengua indígena?"
label variable p3 "¿Sabe usted leer y escribir?"
label variable p4g "¿Cuál fue el último año de escuela que usted aprobó?, GRADO"
label variable p4n "¿Cuál fue el último año de escuela que usted aprobó?, NIVEL"
label variable p4_1 " Ese último año que aprobó, ¿fue en México, Estados Unidos o en otro país?"
label variable p5 "¿Habla usted inglés?"
label variable p5_1 "¿Qué tan bien habla el inglés?"
label variable p6 "¿Cuál es su estado civil?"
label variable p7 "En su casa,¿usted es el jefe del hogar?"
label variable p7_1 "Entonces me puede decir, ¿qué es usted del jefe del hogar?"
label variable p8 "Incluyéndose usted, ¿cuántas personas en total, viven en su casa?"
label variable p8_1 "Del total de personas en la casa donde vive actualmente, ¿cuántas de ellas tienen menos de 15 años de edad?"
label variable p8_2 "Incluyéndose usted, ¿cuántas personas trabajan?"
label variable p8_3 "Incluyéndose usted, ¿cuántas de las que trabajan aportan un ingreso económico al hogar?"
label variable p9_pai "¿En qué país, estado, municipio y localidad nació usted?, PAÍS"
label variable p9e_9m "¿En qué país, estado, municipio y localidad nació usted?, ESTADO-MUNICIPIO"
label variable p9_est "¿En qué país, estado, municipio y localidad nació usted?, ESTADO"
label variable p9_mun "¿En qué país, estado, municipio y localidad nació usted?, MUNICIPIO"
label variable p9_loc "¿En qué país, estado, municipio y localidad nació usted?, LOCALIDAD"
label variable p9_1 "¿El lugar donde vive es el mismo donde usted nació?"
label variable p10_pai "Entonces, ¿en qué estado o país, municipio y localidad vive usted?, PAÍS"
label variable p10e_10m "Entonces, ¿en qué estado o país, municipio y localidad vive usted?, ESTADO-MUNICIPIO"
label variable p10_est "Entonces, ¿en qué estado o país, municipio y localidad vive usted?, ESTADO"
label variable p10_mun "Entonces, ¿en qué estado o país, municipio y localidad vive usted?, MUNICIPIO"
label variable p10_loc "Entonces, ¿en qué estado o país, municipio y localidad vive usted?, LOCALIDAD"
label variable p11 "¿Ha trabajado usted en el lugar donde vive o en algún lugar cercano?"
label variable p11_1 "¿Por qué no ha trabajado en ese lugar?"
label variable p11_2 "Durante los 30 días anteriores al inicio de este viaje, ¿trabajó usted en alguno de esos lugares?"
label variable p11_3 "No trabajó:"
label variable p11_3_1c "¿Cuánto tiempo buscó trabajo?, CANTIDAD"
label variable p11_3_1t "¿Cuánto tiempo buscó trabajo?, TIEMPO"
label variable p11_4 "¿Cuál fue la razón principal por la que dejó su último trabajo?"
label variable p12_1 "¿Cuál es el nombre del oficio o profesión que desempeñó en ese trabajo?"
label variable p12_2 "De la siguiente lista, ¿qué puesto o posición tenía usted en ese trabajo?"
label variable p12_3 "Al momento de ser empleado, ¿firmó contrato de trabajo con el patrón o empresa?"
label variable p12_4 "En ese trabajo que desempeñó, ¿tenía alguna prestación o beneficio?"
label variable p12_4_1 "¿Cuál?"
label variable p12_5 "¿Cuántas horas diarias trabajó en promedio?"
label variable p12_6 "¿Cuántos días a la semana?"
label variable p12_7c "¿Cuánto ganaba en ese trabajo?, CANTIDAD"
label variable p12_7u "¿Cuánto ganaba en ese trabajo?, UNIDAD"
label variable p12_7t "¿Cuánto ganaba en ese trabajo?, TIEMPO"
label variable p12_8 "¿Recibió algún curso de capacitación en la empresa donde trabajó?"
label variable p12_9 "Aproximadamente, ¿cuántas personas, incluyéndose usted, laboraban en el establecimiento donde trabajó?"
label variable p12_10 "¿A qué se dedicaba o que producía el establecimiento, negocio, fábrica o empresa donde trabajó?"
label variable p12_11 "¿El lugar donde realizó sus actividades laborales es:"
label variable p12_12 "Principalmente, ¿de qué manera aprendió el oficio al que se dedicó?"
label variable p13 "Antes de emprender este viaje, ¿visitó a un médico o un centro de salud como preparativo para el viaje?"
label variable p13_1_1 "Antes de emprender este viaje, ¿alguna autoridad o institución le proporcionó a usted alguna información de los siguientes temas de salud?, Prevención de accidentes"
label variable p13_1_2 "Antes de emprender este viaje, ¿alguna autoridad o institución le proporcionó a usted alguna información de los siguientes temas de salud?, Prevención de adicciones"
label variable p13_1_3 "Antes de emprender este viaje, ¿alguna autoridad o institución le proporcionó a usted alguna información de los siguientes temas de salud?, Manejo de enfermedades"
label variable p13_1_4 "Antes de emprender este viaje, ¿alguna autoridad o institución le proporcionó a usted alguna información de los siguientes temas de salud?, Deshidratación"
label variable p13_1_5 "Antes de emprender este viaje, ¿alguna autoridad o institución le proporcionó a usted alguna información de los siguientes temas de salud?, Manejo de cartilla de salud"
label variable p13_2 "Durante el viaje a esta frontera, ¿recibió atención de salud ya sea por enfermedad, lesión o accidente?"
label variable p13_3 "¿Cuál es la principal causa por la que no recibió atención en salud durante este viaje?"
label variable p13_4 "Durante este viaje, ¿sufrió usted una lesión tal como: cortada, herida, hueso roto, torcedura o quemadura?"
label variable p13_5 "¿Qué le causó esta lesión?"
label variable p14 "En los últimos 12 meses, ¿cuántas veces ha llegado a ésta u otra ciudad fronteriza por la misma razón que en este viaje?"
label variable p15 "¿Es la primera vez que viene a esta ciudad por la misma razón?"
label variable p15_1a "¿En qué año la visitó la última vez por esta misma razón?"
label variable p15_2 "¿Tenía usted familiares o amigos en esta ciudad?"
label variable p15_2_1 "¿Cuáles de las siguientes ayudas le proporcionaron?, Préstamo monetario"
label variable p15_2_2 "¿Cuáles de las siguientes ayudas le proporcionaron?, Alojamiento y/o alimentos"
label variable p15_2_3 "¿Cuáles de las siguientes ayudas le proporcionaron?, Ayuda para conseguir trabajo"
label variable p15_2_4 "¿Cuáles de las siguientes ayudas le proporcionaron?, Ellos lo emplearon"
label variable p15_2_5 "¿Cuáles de las siguientes ayudas le proporcionaron?, Ayuda para cruzar a Estados Unidos"
label variable p15_2_6 "¿Cuáles de las siguientes ayudas le proporcionaron?, Otra"
label variable p15_3c "¿Cuánto tiempo permaneció aquí?, CANTIDAD"
label variable p15_3t "¿Cuánto tiempo permaneció aquí?, TIEMPO"
label variable p16c "Ahora, en esta ocasión, ¿cuánto tiempo piensa permanecer en esta ciudad?, CANTIDAD"
label variable p16t "Ahora, en esta ocasión, ¿cuánto tiempo piensa permanecer en esta ciudad?, TIEMPO"
label variable p16_1 "¿Tiene usted familiares o amigos en esta ciudad?"
label variable p16_2 "¿Dónde piensa pasar la noche, el día de hoy?"
label variable p16_3 "¿Va a trabajar o buscar trabajo en esta ciudad?"
label variable p16_3_1 "¿En cuál de los siguientes sectores de la economía piensa usted trabajar?"
label variable p17 "¿Piensa usted pasar a Estados Unidos?"
label variable p17_1 "¿Piensa usted hacerlo en los próximos 30 días?"
label variable p17_2 "¿Por cuál ciudad mexicana va usted a cruzar?"
label variable p17_3 "Principalmente,¿por qué eligió esa ciudad para cruzar?"
label variable p18 "¿Contrató o contratará usted a alguna persona (coyote, pollero, guía, lanchero, patero) para que lo ayude a cruzar la frontera?"
label variable p18_1 "¿Dónde hizo o hará el contacto con la persona que lo ayudará a cruzar la frontera?"
label variable p18_2c "¿Cuánto pagó o acordó pagar?, CANTIDAD"
label variable p18_2u "¿Cuánto pagó o acordó pagar?, UNIDAD"
label variable p19 "Principalmente, ¿por cuál de las siguientes razones cruzará usted al otro lado?"
label variable p20 "En su destino final, ¿tiene usted un trabajo ya asegurado?"
label variable p20_1 "¿En cuál de los siguientes sectores de la economía piensa trabajar usted?"
label variable p21 "¿Se dirige a alguna ciudad en especial?"
label variable p21e_21o "¿A cuál ciudad, condado y estado se dirige?, ESTADO-CONDADO"
label variable p21_1c "¿A cuál ciudad, condado y estado se dirige?, CIUDAD"
label variable p21_1o "¿A cuál ciudad, condado y estado se dirige?, CONDADO"
label variable p21_1e "¿A cuál ciudad, condado y estado se dirige?, ESTADO"
label variable p21_2_1 "¿Alguno de los siguientes familiares vive en esa ciudad?, Esposa (o) o pareja"
label variable p21_2_2 "¿Alguno de los siguientes familiares vive en esa ciudad?, Hijos (as)"
label variable p21_2_3 "¿Alguno de los siguientes familiares vive en esa ciudad?, Padre y/o madre"
label variable p21_2_4 "¿Alguno de los siguientes familiares vive en esa ciudad?, Hermanos (as)"
label variable p21_2_5 "¿Alguno de los siguientes familiares vive en esa ciudad?, Otros familiares"
label variable p21_3 "En su destino final,¿tiene usted un lugar fijo donde llegar?"
label variable p22c "¿Cuánto tiempo piensa quedarse en Estados Unidos?, CANTIDAD"
label variable p22t "¿Cuánto tiempo piensa quedarse en Estados Unidos?, TIEMPO"
label variable p23 "¿Tiene documentos para cruzar?"
label variable p23_1 "¿Cuál documento tiene?"
label variable p23_2c "¿Desde cuándo lo tiene?, CANTIDAD"
label variable p23_2t "¿Desde cuándo lo tiene?, TIEMPO"
label variable p24 "¿Tiene documentos para trabajar?"
label variable p24_1 "¿Cuál documento tiene?"
label variable p24_2c "¿Desde cuándo lo tiene?, CANTIDAD"
label variable p24_2t "¿Desde cuándo lo tiene?, TIEMPO"
label variable p25 "¿Ha realizado algún trámite oficial con la finalidad de obtener documentos para:"
label variable p26 "En total,¿cuántas veces ha cruzado a Estados Unidos para trabajar o buscar trabajo?"
label variable p26_1a "¿En qué año fue la primera vez que cruzó a Estados Unidos a trabajar o buscar trabajo?"
label variable p26_2 "En esa ocasión, ¿usó usted algún tipo de documento para cruzar a Estados Unidos?"
label variable p27m "¿En qué mes y año fue la última vez que cruzó a Estados Unidos para trabajar o buscar trabajo?, MES"
label variable p27a "¿En qué mes y año fue la última vez que cruzó a Estados Unidos para trabajar o buscar trabajo?, AÑO"
label variable p28 "Esa última vez, ¿por cuál ciudad mexicana cruzó usted?"
label variable p29 "En esa ocasión, ¿contrató usted a alguna persona (coyote, pollero, guía, lanchero, patero) para que lo ayudara a cruzar la frontera?"
label variable p30 "En esa ocasión, ¿usó usted algún tipo de documento para cruzar a Estados Unidos?"
label variable p31 "En esa última ocasión que cruzó a Estados Unidos, ¿llevaba usted algún documento para trabajar?"
label variable p32c "En esa ocasión, ¿cuánto tiempo permaneció usted en Estados Unidos?, CANTIDAD"
label variable p32t "En esa ocasión, ¿cuánto tiempo permaneció usted en Estados Unidos?, TIEMPO"
label variable p33 "¿En qué estado estuvo usted la mayor parte del tiempo?"
label variable p33_1 "¿Tenía usted familiares o amigos en ese estado?"
label variable p34 "En esa ocasión, ¿trabajó usted en Estados Unidos?"
label variable p34_1 "¿Cuántos trabajos diferentes tuvo en Estados Unidos?"
label variable p35_1 "¿Cuál es el nombre del oficio o profesión que desempeñó en ese trabajo?"
label variable p35_2 "¿Cuántas horas diarias trabajó en promedio?"
label variable p35_3 "¿Cuántos días a la semana?"
label variable p35_4 "¿A qué se dedicaba o qué producía el establecimiento, negocio, fábrica o empresa donde trabajó?"
label variable p36 "Principalmente, ¿por cuál razón regresó usted a México?"
label variable p37 "En general, ¿cómo considera usted su estado de salud?"
label variable p38_1 "¿Tiene derecho a los servicios médicos de(l): Seguro Popular?"
label variable p38_2 "¿Tiene derecho a los servicios médicos de(l): IMSS?"
label variable p38_3 "¿Tiene derecho a los servicios médicos de(l): ISSSTE?"
label variable p38_4 "¿Tiene derecho a los servicios médicos de(l): Oportunidades?"
label variable p38_5 "¿Tiene derecho a los servicios médicos de(l): Otra institución?"
label variable p39_1 "En los últimos 15 días, ¿ha presentado algunos de los siguientes síntomas?, Fiebre"
label variable p39_2 "En los últimos 15 días, ¿ha presentado algunos de los siguientes síntomas?, Diarrea"
label variable p39_3 "En los últimos 15 días, ¿ha presentado algunos de los siguientes síntomas?, Tos"
label variable p39_4 "En los últimos 15 días, ¿ha presentado algunos de los siguientes síntomas?, Poco interés de hacer cosas"
label variable p39_5 "En los últimos 15 días, ¿ha presentado algunos de los siguientes síntomas?, Tristeza"
label variable p39_6 "En los últimos 15 días, ¿ha presentado algunos de los siguientes síntomas?, Desesperación"
label variable p40_1 "¿Algún médico o profesional de la salud le ha dicho que usted tiene: hipertensión (Presión Alta)?"
label variable p40_2 "¿Algún médico o profesional de la salud le ha dicho que usted tiene: diabetes (Problemas de Azúcar)?"
label variable p40_3 "¿Algún médico o profesional de la salud le ha dicho que usted tiene: colesterol (Problemas de grasas en sangre)?"
label variable p40_4 "¿Algún médico o profesional de la salud le ha dicho que usted tiene: tuberculosis?"
label variable p40_5 "¿Algún médico o profesional de la salud le ha dicho que usted tiene: depresión?"
label variable p40_6 "¿Algún médico o profesional de la salud le ha dicho que usted tiene: ansiedad?"
label variable p40_7 "¿Algún médico o profesional de la salud le ha dicho que usted tiene: otra enfermedad grave?"
label variable p41_1 "¿Conoce los siguientes programas de salud que el gobierno mexicano tiene para los migrantes? Ventanillas de salud"
label variable p41_2 "¿Conoce los siguientes programas de salud que el gobierno mexicano tiene para los migrantes? Vete Sano, Regresa Sano"
label variable p41_3 "¿Conoce los siguientes programas de salud que el gobierno mexicano tiene para los migrantes? Salud del Migrante"
label variable p41_4 "¿Conoce los siguientes programas de salud que el gobierno mexicano tiene para los migrantes? Asistencia a repatriados"
label variable ponfin3 "Ponderador final"
