label variable folio "Folio"
label variable tiem_h "Tiempo en horas"
label variable tiem_m "Tiempo en minutos"
label variable reg_mue "Región de muestreo"
label variable cd_mue "Ciudad de muestreo"
label variable zona_mue "Zona de muestreo"
label variable punt_mue "Punto de muestreo"
label variable turno "Turno"
label variable tot_per "Número total de personas"
label variable sexo "Sexo"
label variable edad "Edad"
label variable pai_nac "¿Dónde nació usted?"
label variable origen "¿Es usted de origen mexicano o México-americano?"
label variable vive "¿Vive usted aquí en (localidad de entrevista)?"
label variable pais_vive "¿En qué país vive?"
label variable razon "¿Por cuál de las siguientes razones se debe su visita a la zona fronteriza?"
label variable trabaja "¿Tiene usted trabajo en su lugar de procedencia o alguna fecha comprometida para su regreso?"
label variable num_per "Número de personas de renglón a renglón"
label variable ren_inf "Renglón del Informante"
label variable p1 "¿Viene usted solo o acompañado en este viaje?"
label variable p1_1 "¿Cuántas personas lo acompañan?"
label variable p1_2 "¿Cuántas de ellas son menores de 15 años?"
label variable p1_3 "¿Cuántas de ellas son sus padres, hermanos, hijos o esposa?"
label variable p1_4 "De las personas que lo acompañan, ¿cuántas nacieron en México?"
label variable p1_5 "De las personas que lo acompañan, ¿cuántas son mujeres?"
label variable p2 "En general, ¿cómo considera usted su estado de salud?"
label variable p3 "¿Habla usted algún dialecto o lengua indígena?"
label variable p4 "¿Sabe usted leer y escribir?"
label variable p4_1gra "¿Cuál fue el último año de escuela que usted aprobó? (grado)"
label variable p4_1niv "¿Cuál fue el último año de escuela que usted aprobó? (nivel)"
label variable p4_1_1 "Ese último año que aprobó, ¿fue en México, Estados Unidos o en otro país?"
label variable p5 "¿Habla usted inglés?"
label variable p5_1 "¿Qué tan bien habla el inglés?"
label variable p6 "¿Cuál es su estado civil?"
label variable p7 "En su casa, ¿es usted el jefe del hogar?"
label variable p7_1 "Entonces, me puede decir, ¿qué es usted del jefe del hogar?"
label variable p8 "Incluyéndose  usted, en total, ¿cuántas personas viven en su casa?"
label variable p8_1 "Del total de personas en la casa donde vive actualmente, ¿cuántas de ellas tienen menos de 15 años de edad?"
label variable p8_2 "Incluyéndose usted, ¿cuántas personas trabajan?"
label variable p8_2_1 "Incluyéndose usted, ¿cuántas de las que trabajan, aportan un ingreso económico al hogar?"
label variable p9_pai "¿En qué país nació usted?"
label variable p9_est "¿En qué estado nació usted?"
label variable p9_mun "¿En qué municipio nació usted?"
label variable p9_loc "¿En qué localidad nació usted?"
label variable p9_1 "¿El lugar donde vive es el mismo donde usted nació?"
label variable p10_pai "Entonces, ¿en qué país vive usted?"
label variable p10_est "Entonces, ¿en qué estado vive usted?"
label variable p10_mun "Entonces, ¿en qué municipio vive usted?"
label variable p10_loc "Entonces, ¿en qué localidad vive usted?"
label variable p11 "¿Ha trabajado usted alguna vez en ese lugar o en algún lugar cercano?"
label variable p11_1 "¿Por qué no ha trabajado en ese lugar?"
label variable p11_2 "Durante los treinta días anteriores al inicio de su último viaje a Estados Unidos, ¿trabajó usted en alguno de esos lugares?"
label variable p11_3 "No trabajó:"
label variable p11_3_1c "¿Cuánto tiempo buscó trabajo? (cantidad)"
label variable p11_3_1t "¿Cuánto tiempo buscó trabajo? (tiempo)"
label variable p12 "Durante su  último empleo en México, ¿cuántas horas diarias trabajó en promedio?"
label variable p12_1 "¿Cuántos días a la semana?"
label variable p12_2c "¿Cuánto ganaba en ese trabajo? (cantidad)"
label variable p12_2u "¿Cuánto ganaba en ese trabajo? (unidad)"
label variable p12_2t "¿Cuánto ganaba en ese trabajo? (tiempo)"
label variable p12_3 "¿Cuál es el nombre del oficio o profesión que desempeñó en ese trabajo?"
label variable p12_4 "¿A qué se dedicaba o qué producía el establecimiento, negocio, fábrica o empresa donde trabajó?"
label variable p12_5 "¿En qué país aprendió el oficio al que se dedicó?"
label variable p12_6 "Principalmente ¿de qué manera aprendió el oficio al que se dedicó?"
label variable p12_7 "¿Recibió algún curso de capacitación en la empresa donde trabajó?"
label variable p12_8 "De la siguiente lista, ¿qué puesto o posición tenía usted en ese trabajo?"
label variable p12_9 "Al momento de ser empleado, ¿firmó contrato de trabajo con el patrón o empresa?"
label variable p12_10 "En el trabajo que desempeñó ¿tenía algún beneficio o prestación?"
label variable p12_10_1 "¿Cuál?"
label variable p12_11 "¿Cuál fue la razón principal por la que dejó su último trabajo?"
label variable p12_12 "Aproximadamente, ¿cuántas personas, incluyéndose usted, laboraban en el establecimiento donde trabajó?"
label variable p12_13 "El lugar donde realizó sus actividades es:"
label variable p13 "En los últimos 12 meses, ¿cuántas veces ha llegado a ésta u otra ciudad fronteriza por la misma razón que en este viaje?"
label variable p14 "¿Es la primera vez que viene a esta ciudad por la misma razón?"
label variable p14_1 "¿En qué año la visitó la última vez por esta misma razón?"
label variable p14_2 "¿Tenía usted familiares o amigos en esta ciudad?"
label variable p14_2_1_1 "¿Cuáles de las siguientes ayudas le proporcionaron? Préstamo monetario"
label variable p14_2_1_2 "¿Cuáles de las siguientes ayudas le proporcionaron? Alojamiento y/o alimentos"
label variable p14_2_1_3 "¿Cuáles de las siguientes ayudas le proporcionaron? Ayuda para conseguir trabajo"
label variable p14_2_1_4 "¿Cuáles de las siguientes ayudas le proporcionaron? Ellos lo emplearon"
label variable p14_2_1_5 "¿Cuáles de las siguientes ayudas le proporcionaron? Ayuda para cruzar a Estados Unidos"
label variable p14_2_1_6 "¿Cuáles de las siguientes ayudas le proporcionaron? Otra"
label variable p14_3c "¿Cuánto tiempo permaneció aquí? (cantidad)"
label variable p14_3t "¿Cuánto tiempo permaneció aquí? (tiempo)"
label variable p14_4 "Durante el tiempo que estuvo en esta ciudad, ¿trabajó usted aquí?"
label variable p14_4_1 "El establecimiento, negocio, fábrica o empresa donde trabajó, ¿era una maquiladora?"
label variable p14_4_2 "¿A qué se dedicaba o qué producía el establecimiento, negocio, fábrica o empresa donde trabajó?"
label variable p15c "Ahora, en esta ocasión, ¿cuánto tiempo piensa permanecer en esta ciudad? (cantidad)"
label variable p15t "Ahora, en esta ocasión, ¿cuánto tiempo piensa permanecer en esta ciudad? (tiempo)"
label variable p15_1 "¿Tiene usted familiares o amigos en esta ciudad?"
label variable p15_2 "¿Dónde piensa pasar la noche, el día de hoy?"
label variable p15_3 "¿Va a trabajar o buscar trabajo en esta ciudad?"
label variable p15_3_1 "¿En cuál de los siguientes sectores de la economía piensa usted trabajar?"
label variable p16 "¿Piensa usted pasar a Estados Unidos?"
label variable p16_1 "¿Piensa usted hacerlo en los próximos 30 días?"
label variable p16_2 "¿Por cuál ciudad Mexicana va usted a cruzar?"
label variable p16_3 "Principalmente ¿por qué eligió esa ciudad para cruzar?"
label variable p17 "Principalmente, ¿por cuál de las siguientes razones cruzará usted al otro lado?"
label variable p18 "En su destino final, ¿tiene usted un trabajo ya asegurado?"
label variable p18_1 "¿En cuál de los siguientes sectores de la economía piensa trabajar usted?"
label variable p19 "¿Se dirige a alguna ciudad en especial?"
label variable p19_1c "¿A cuál ciudad?"
label variable p19_1o "¿A cuál condado?"
label variable p19_1e "¿A cuál estado?"
label variable p19_2_1 "¿Alguno de los siguientes familiares vive en esa ciudad? (Esposa y/o pareja)"
label variable p19_2_2 "¿Alguno de los siguientes familiares vive en esa ciudad? (Hijos (as))"
label variable p19_2_3 "¿Alguno de los siguientes familiares vive en esa ciudad? (Padre y /o madre)"
label variable p19_2_4 "¿Alguno de los siguientes familiares vive en esa ciudad? (Hermanos (as))"
label variable p19_2_5 "¿Alguno de los siguientes familiares vive en esa ciudad? (Otros familiares)"
label variable p19_3 "En su destino final, ¿tiene usted un lugar fijo donde llegar?"
label variable p20c "¿Cuánto tiempo piensa quedarse en Estados Unidos? (cantidad)"
label variable p20t "¿Cuánto tiempo piensa quedarse en Estados Unidos? (tiempo)"
label variable p21 "¿Contrató o contratará usted a alguna persona (coyote, pollero, guía, lanchero, patero) para que lo ayude a cruzar la frontera?"
label variable p21_1 "¿Dónde hizo o hará el contacto con la persona que lo ayudará a cruzar la frontera?"
label variable p21_2c "¿Cuánto acordó pagar? (cantidad)"
label variable p21_2u "¿Cuánto acordó pagar? (unidad)"
label variable p22 "¿Tiene documentos para cruzar?"
label variable p22_1 "¿Cuál documento tiene?"
label variable p22_2c "¿Desde cuando lo tiene? (cantidad)"
label variable p22_2t "¿Desde cuando lo tiene? (tiempo)"
label variable p23 "¿Tiene documentos para trabajar?"
label variable p23_1 "¿Cuál documento tiene?"
label variable p23_2c "¿Desde cuándo lo tiene? (cantidad)"
label variable p23_2t "¿Desde cuándo lo tiene? (tiempo)"
label variable p24 "¿Ha realizado algún trámite oficial con la finalidad de obtener documentos para?"
label variable p25 "En total, ¿cuántas veces ha cruzado a Estados Unidos para trabajar o buscar trabajo?"
label variable p25_1 "¿En qué año fue la primera vez que cruzó a Estados Unidos a trabajar o buscar  trabajo?"
label variable p25_2 "En esa ocasión, ¿usó usted algún tipo de documento para cruzar a Estados Unidos?"
label variable p26m "¿En qué mes y año fue la última vez que cruzó a Estados Unidos para trabajar o buscar trabajo? (mes)"
label variable p26a "¿En qué mes y año fue la última vez que cruzó a Estados Unidos para trabajar o buscar trabajo? (año)"
label variable p27 "Esa última vez, ¿por cuál ciudad mexicana cruzó usted?"
label variable p28 "En esa ocasión, ¿contrató usted a alguna persona (coyote, pollero, guía, lanchero, patero) para que lo ayudara a cruzar la frontera?"
label variable p29 "En esa ocasión, ¿usó usted algún tipo de documento para cruzar a Estados Unidos?"
label variable p30 "En esa última ocasión que cruzó a E.U., ¿llevaba usted algún documento para trabajar?"
label variable p31c "En esa ocasión,  ¿cuánto tiempo permaneció usted en Estados Unidos? (cantidad)"
label variable p31t "En esa ocasión,  ¿cuánto tiempo permaneció usted en Estados Unidos? (tiempo)"
label variable p32 "¿En qué estado estuvo usted la mayor parte del tiempo?"
label variable p32_1 "¿Tenía usted familiares o amigos en ese estado?"
label variable p33 "En esa ocasión, ¿trabajó usted en Estados Unidos?"
label variable p33_1 "¿Cuántos trabajos diferentes tuvo en Estados Unidos?"
label variable p34 "Durante su  último empleo en Estados Unidos, ¿cuántas horas diarias trabajó en promedio?"
label variable p34_1 "¿Cuántos días a la semana?"
label variable p34_2c "Aproximadamente, ¿cuántos dólares ganaba usted? (cantidad)"
label variable p34_2t "Aproximadamente, ¿cuántos dólares ganaba usted? (tiempo)"
label variable p34_3 "¿Cuál es el nombre del oficio o profesión que desempeñó en ese trabajo?"
label variable p34_4 "¿A qué se dedicaba o qué producía el establecimiento, negocio, fábrica o empresa donde trabajó?"
label variable p34_5 "De la siguiente lista, ¿qué puesto o posición tenía usted en ese trabajo?"
label variable p34_5_1 "Al momento de ser empleado, ¿firmó contrato de trabajo con el patrón o empresa?"
label variable p34_6 "En el trabajo que desempeñó, ¿tenía algún beneficio o prestación?"
label variable p34_6_1 "¿Cuáles?"
label variable p35 "En esa ocasión, ¿envió usted dólares a su país de origen?"
label variable p35_1c "¿Cada cuándo envió dólares a su país de origen? (cantidad)"
label variable p35_1t "¿Cada cuándo envió dólares a su país de origen? (tiempo)"
label variable p35_2 "En cada envío ¿cuántos dólares mandó?"
label variable p36 "Principalmente, ¿por cuál de las siguientes razones regresó usted a México?"
label variable ponfin3 "Factor de expansión"
label variable unidad ""
label variable trim "Trimestre"
