label variable folio "Folio"
label variable f_dia "Fecha día"
label variable f_mes "Fecha mes"
label variable f_ano "Fecha año"
label variable tiem_h "Tiempo en horas"
label variable tiem_m "Tiempo en minutos"
label variable reg_mue "Región de muestreo"
label variable zona_mue "Zona de muestreo"
label variable cd_mue "Ciudad de muestreo"
label variable punt_mue "Punto de muestreo"
label variable pondera "Ponderador"
label variable turno "Turno"
label variable tot_per "Número total de personas"
label variable ren_inf "Renglón del informante"
label variable dia_sem "Día de la semana"
label variable tij_tec "Procede de Tijuana o Tecate"
label variable sexo "Sexo"
label variable edad "Edad"
label variable locali "Localidad"
label variable mun_nac "Municipio de nacimiento"
label variable pai_nac "País o estado de nacimiento"
label variable vie_ud "En qué estado o país inició este viaje"
label variable vive "Vive usted aquí en localidad de la entrevista"
label variable razon "Razón de visita a la zona fronteriza"
label variable trabaja "Tiene trabajo en lugar de procedencia"
label variable num_per "Número de personas de renglón a renglón"
label variable p1 "¿Viene usted solo o acompañado en este viaje?"
label variable p1_1 "¿Cuántas personas lo acompañan?"
label variable p1_2 "¿Cuántas de ellas son menores de 12 años?"
label variable p1_3 "¿Cuántas de ellas son sus padres, hermanos, hijos o esposa?"
label variable p1_4 "De las personas que lo acompañan, ¿cuántas nacieron en México?"
label variable p1_5 "De las personas que lo acompañan, ¿cuántas son mujeres?"
label variable p2 "¿Habla usted algún dialecto o lengua indígena?"
label variable p2_1 "¿Sabe usted leer y escribir?"
label variable p2_2gra "¿Cuál fue el último año de escuela que usted aprobó? (grado)"
label variable p2_2niv "¿Cuál fue el último año de escuela que usted aprobó? (nivel)"
label variable p2_3 "¿Habla usted inglés?"
label variable p2_3_1 "¿Qué tan bien habla el inglés?"
label variable p3 "¿Cuál es su estado civil?"
label variable p4 "En su casa, ¿usted es el jefe del hogar?"
label variable p4_1 "Entonces me puede decir, ¿qué es usted del jefe del hogar?"
label variable p5 "Incluyéndose usted, ¿cuántas personas en total  viven en su casa?"
label variable p5_1 "Incluyéndose usted, ¿cuántas de ellas trabajan?"
label variable p5_1_1 "Incluyéndose usted, ¿cuántas de las que trabajan aportan un ingreso económico al hogar?"
label variable p6_pai "¿En qué estado o país, municipio y localidad  vive usted? (país)"
label variable p6_est "¿En qué estado o país, municipio y localidad  vive usted? (estado)"
label variable p6_mun "¿En qué estado o país, municipio y localidad  vive usted? (municipio)"
label variable p6_loc "¿En qué estado o país, municipio y localidad  vive usted? (localidad)"
label variable p7c "¿Cuánto tiempo tiene de vivir en esa localidad? (cantidad)"
label variable p7t "¿Cuánto tiempo tiene de vivir en esa localidad? (tiempo)"
label variable p8 "¿Ha trabajado usted en el lugar donde vive o en algún lugar cercano?"
label variable p8_1 "Durante los 30 días anteriores al inicio de este viaje, ¿trabajó usted en alguno de esos lugares?"
label variable p8_1_1 "No trabajó:"
label variable p8_1_2c "¿Cuánto tiempo buscó trabajo? (cantidad)"
label variable p8_1_2t "¿Cuánto tiempo buscó trabajo? (tiempo)"
label variable p8_2 "¿Cuántas horas diarias en promedio trabajaba?"
label variable p8_3 "¿Cuántos días a la semana?"
label variable p8_4c "¿Cuánto ganaba en ese trabajo? (cantidad)"
label variable p8_4u "¿Cuánto ganaba en ese trabajo? (unidad)"
label variable p8_4t "¿Cuánto ganaba en ese trabajo? (tiempo)"
label variable p8_5 "¿Cuál es el nombre del oficio o profesión que desempeñó en ese trabajo?"
label variable p8_6 "¿Dónde aprendió el oficio al que se dedicó?"
label variable p8_7 "¿A qué se dedicaba o qué producía el establecimiento, negocio, fábrica o empresa donde trabajó?"
label variable p8_7_1 "Aproximadamente, ¿cuántas personas, incluyéndose usted, laboran en el establecimiento donde trabajó?"
label variable p8_7_2 "El lugar donde realizó sus actividades es:"
label variable p8_8 "De la siguiente lista, ¿qué puesto o posición tenía usted en ese trabajo?"
label variable p8_8_1 "Al momento de ser empleado ¿firmó contrato de trabajo con el patrón o empresa?"
label variable p8_9 "En el trabajó que desempeñó ¿tenía alguna prestación o beneficio?"
label variable p8_9_1 "¿Cuál prestación o beneficio?"
label variable p8_10 "Principalmente, ¿de qué manera aprendió el oficio al que se dedicó?"
label variable p8_10_1 "¿Recibió algún curso de capacitación en la empresa donde trabajó?"
label variable p8_10_2 "¿El curso de capacitación tenía alguna relación con el oficio desempeñado?"
label variable p8_10_3 "En ese trabajó, ¿desempeñó el mismo oficio que regularmente ha desempeñado?"
label variable p8_10_4c "¿Cuánto tiempo duró trabajando en su último empleo? (cantidad)"
label variable p8_10_4t "¿Cuánto tiempo duró trabajando en su último empleo? (tiempo)"
label variable p8_10_5 "¿Cuál fue la razón principal por la que dejó su último trabajo?"
label variable p9 "¿Cuánto tiempo tiene de haber salido del lugar donde vive?"
label variable p10 "¿Es la primera vez que viene a esta ciudad?"
label variable p10_1 "¿En qué año la visitó la última vez?"
label variable p10_1_1 "¿Tenía usted familiares o amigos en esta ciudad?"
label variable p10_1_21 "¿Qué tipo de ayuda le proporcionaron? préstamo monetario"
label variable p10_1_22 "¿Qué tipo de ayuda le proporcionaron? alojamiento y/o alimentos"
label variable p10_1_23 "¿Qué tipo de ayuda le proporcionaron? ayuda para conseguir trabajo"
label variable p10_1_24 "¿Qué tipo de ayuda le proporcionaron? ellos lo emplearon"
label variable p10_1_25 "¿Qué tipo de ayuda le proporcionaron? ayuda para cruzar a EUA"
label variable p10_1_26 "¿Qué tipo de ayuda le proporcionaron? otra"
label variable p10_2c "¿Cuánto tiempo permaneció aquí? (cantidad)"
label variable p10_2t "¿Cuánto tiempo permaneció aquí?  (tiempo)"
label variable p10_2_1 "Durante el tiempo que estuvo en esta ciudad, ¿trabajó usted aquí?"
label variable p10_2_11 "El establecimiento, negocio, fábrica o empresa donde trabajó, ¿era una maquiladora?"
label variable p10_2_12 "A qué se dedicaba o qué producía  el establecimiento, negocio, fábrica o empresa donde trabajó?"
label variable p10_213c "¿Durante los últimos 30 días que trabajó usted cuánto dinero ganó? (cantidad)"
label variable p10_213u "¿Durante los últimos 30 días que trabajó usted cuánto dinero ganó? (unidad)"
label variable p102131c "De esa cantidad, ¿cuánto dinero envió usted al lugar donde vivía? (cantidad)"
label variable p102131u "De esa cantidad, ¿cuánto dinero envió usted al lugar donde vivía? (unidad)"
label variable p11c "Ahora, en esta ocasión, ¿cuánto tiempo piensa permanecer en esta ciudad? (cantidad)"
label variable p11t "Ahora, en esta ocasión, ¿cuánto tiempo piensa permanecer en esta ciudad? (tiempo)"
label variable p11_1 "Dónde piensa pasar la noche, el día de hoy?"
label variable p11_2 "Va a trabajar o buscar trabajo en esta ciudad?"
label variable p11_2_1 "¿En cuál de los siguientes sectores  de la economía piensa usted trabajar?"
label variable p12c "¿Cuánto dinero gastó en este viaje desde que salió de su casa o del lugar donde vivía? (cantidad)"
label variable p12u "¿Cuánto dinero gastó en este viaje desde que salió de su casa o del lugar donde vivía? (unidad)"
label variable p12_1 "¿Le prestaron algo de ese dinero?"
label variable p13 "¿Piensa usted pasar al otro lado?"
label variable p13_1 "¿Piensa usted hacerlo en los próximo 30 días?"
label variable p13_1a "Por cuál ciudad Mexicana va usted a cruzar?"
label variable p13_1b "Principalmente ¿por qué eligió esa ciudad para cruzar?"
label variable p13_1_1 "¿Tiene usted un lugar fijo donde llegar?"
label variable p13_2 "Principalmente, ¿por cuál de las siguientes razones cruzará usted al otro lado?"
label variable p13_2_1 "En su destino final, ¿tiene usted un trabajo ya asegurado?"
label variable p13_2_2 "En cuál de los siguientes sectores de la economía piensa trabajar usted?"
label variable p13_3 "¿Se dirige a alguna ciudad en especial?"
label variable p13_3_1c "¿A cuál? (ciudad)"
label variable p13_3_1o "¿A cuál? (condado)"
label variable p13_3_1e "¿A cuál? (estado)"
label variable p13_4c "¿Cuánto tiempo piensa quedarse en Estados Unidos? (cantidad)"
label variable p13_4t "¿Cuánto tiempo piensa quedarse en Estados Unidos? (tiempo)"
label variable p13_4_1 "¿Contrató o contratará usted a alguna persona (coyote, pollero, guía, lanchero, patero) para que lo ayude a cruzar la frontera?"
label variable p13_4_11 "¿Dónde hizo o hará el contacto con la persona que lo ayudará a cruzar la frontera?"
label variable p13_412c "¿Cuánto acordó pagar? (cantidad)"
label variable p13_412u "¿Cuánto acordó pagar? (unidad)"
label variable p13_5 "¿Tiene documentos para cruzar?"
label variable p13_5_1 "¿Cuál documento tiene?"
label variable p13_5_2c "¿Desde cuando lo tiene? (cantidad)"
label variable p13_5_2t "¿Desde cuando lo tiene? (tiempo)"
label variable p13_6 "¿Tiene documentos para trabajar?"
label variable p13_6_1 "¿Cuál documento tiene?"
label variable p13_6_2c "¿Desde cuándo lo tiene? (cantidad)"
label variable p13_6_2t "¿Desde cuándo lo tiene? (tiempo)"
label variable p13_6_3 "Ha realizado algún trámite oficial con la finalidad de obtener documentos para:"
label variable p14 "En total, ¿cuántas veces ha cruzado a Estados Unidos para trabajar o buscar trabajó?"
label variable p14_1 "En qué año fue la primera vez que cruzó a Estados Unidos a trabajar o buscar trabajo?"
label variable p14_2 "En esa ocasión, ¿usó usted algún tipo de documento para cruzar a Estados Unidos?"
label variable p15m "En qué mes y año fue la última vez que cruzó a Estados Unidos para trabajar o buscar trabajo? (mes)"
label variable p15a "En qué mes y año fue la última vez que cruzó a Estados Unidos para trabajar o buscar trabajo? (año)"
label variable p16 "Esa última vez, ¿por cuál ciudad mexicana cruzó usted?"
label variable p16_1c "¿Cuánto tiempo permaneció en esa ciudad antes de cruzar? (cantidad)"
label variable p16_1t "¿Cuánto tiempo permaneció en esa ciudad antes de cruzar? (tiempo)"
label variable p17 "En esa ocasión, ¿contrató usted a alguna persona (coyote, pollero, guía, lanchero, patero) para que lo ayudara a cruzar la frontera?"
label variable p17_a "¿Dónde hizo el contacto con la persona que lo ayudó a cruzar la frontera?"
label variable p18 "En esa ocasión, ¿usó usted algún tipo de documento para cruzar a Estados Unidos?"
label variable p19 "En esa última ocasión que cruzó a E.U., ¿llevaba usted algún documento para trabajar?"
label variable p20c "¿En esa ocasión, ¿cuánto tiempo permaneció usted en Estados Unidos? (cantidad)"
label variable p20t "¿En esa ocasión, ¿cuánto tiempo permaneció usted en Estados Unidos? (tiempo)"
label variable p20_1ciu "¿En qué ciudad, condado y estado estuvo usted la mayor parte del tiempo? (ciudad)"
label variable p20_1con "¿En qué ciudad, condado y estado estuvo usted la mayor parte del tiempo? (condado)"
label variable p20_1est "¿En qué ciudad, condado y estado estuvo usted la mayor parte del tiempo? (estado)"
label variable p20_2 "¿Tenía usted  familiares o amigos en esa ciudad?"
label variable p20_2_11 "¿Qué tipo de ayuda le proporcionaron? préstamo monetario"
label variable p20_2_12 "¿Qué tipo de ayuda le proporcionaron? alojamiento y/o alimentos"
label variable p20_2_13 "¿Qué tipo de ayuda le proporcionaron? ayuda para conseguir trabajo"
label variable p20_2_14 "¿Qué tipo de ayuda le proporcionaron? ellos lo emplearon"
label variable p20_2_15 "¿Qué tipo de ayuda le proporcionaron? ayuda para cruzar a EUA"
label variable p20_2_16 "¿Qué tipo de ayuda le proporcionaron? otra"
label variable p20_3 "En esa ocasión, ¿trabajó usted en Estados Unidos?"
label variable p20_3_1 "En esa ocasión, ¿cuántos trabajos diferentes tuvo en Estados Unidos?"
label variable p20_3_2c "En esa ocasión, en total, ¿cuánto tiempo trabajó en Estados Unidos? (cantidad)"
label variable p20_3_2t "En esa ocasión, en total, ¿cuánto tiempo trabajó en Estados Unidos? (tiempo)"
label variable p20_3_3c "En esa ocasión, ¿cuánto duro el empleo más largo en Estados Unidos (cantidad)"
label variable p20_3_3t "En esa ocasión, ¿cuánto duro el empleo más largo en Estados Unidos (tiempo)"
label variable p20_3_4 "¿Cuántas horas diarias en promedio trabajó?"
label variable p20_3_5 "¿Cuántos días a la semana?"
label variable p20_3_6c "Aproximadamente ¿cuántos dólares ganaba usted? (cantidad)"
label variable p20_3_6d "Aproximadamente ¿cuántos dólares ganaba usted? (decimales)"
label variable p20_3_6t "Aproximadamente ¿cuántos dólares ganaba usted? (tiempo)"
label variable p20_3_7 "¿Cuál es el nombre del oficio o  profesión que desempeñó en ese trabajo?"
label variable p20_3_8 "¿Dónde aprendió el oficio al que se dedicó?"
label variable p20_3_9 "¿A qué se dedicaba o qué producía el establecimiento, negocio, fábrica o empresa dónde trabajó?"
label variable p20_3_91 "Aproximadamente, ¿cuántas personas, incluyéndose usted, laboraban en el establecimiento donde trabajó?"
label variable p20_3_10 "De la siguiente lista, ¿qué puesto o posición tenía usted en ese trabajo?"
label variable p20_3101 "Al momento de ser empleado, ¿firmó contrato de trabajo con el patrón o empresa?"
label variable p20_3_11 "En el trabajo que desempeñó, ¿tenía algún beneficio o prestación?"
label variable p20_3111 "¿Cuáles beneficios o prestaciones?"
label variable p20_3_12 "Principalmente, ¿de qué manera aprendió el oficio al que se dedicó?"
label variable p20_3121 "Recibió algún curso de capacitación en la empresa donde trabajó?"
label variable p20_3122 "En ese trabajo desempeñó el mismo oficio que regularmente ha desempeñado?"
label variable p20_3_13 "Durante los últimos 30 días que trabajó usted, ¿cuántos dólares ganó?"
label variable p20_3131 "De esa cantidad, ¿cuántos dólares envió usted a su país de origen?"
label variable p21 "Principalmente,  ¿por cuál de las siguientes razones regresó usted a su lugar de origen?"
label variable x8_5 "¿Cuál es el nombre del oficio o profesión que desempeñó en ese trabajo?"
label variable x20_3_7 "¿Cuál es el nombre del oficio o profesión que desempeñó en ese trabajo?"
label variable z1 "Es un factor para el calculo de la ponderación"
label variable region "Región de apliación del cuestionario"
label variable fecha "Fecha de aplicación del cuestionario"
label variable trim "Trimestre de la fase XIII"
label variable sur_int "Tipo de migrante"
label variable ponfin3 "Ponderador final (factor de expansión)"
label variable factor "Factor de la ponderación"
